version: '3.3'

services:
  api:
    build: .
    container_name: notes-api
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8022
    volumes:
      - .:/usr/src/app/
    ports:
      - 8022:8022
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/notes_db

  db:
    image: postgres:12
    container_name: notes-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_db

volumes:
  postgres_data:
