version: '3.9'

services:
  api:
    build: .
    image: notes-api:arm64
    container_name: notes-api
    volumes:
      - venv:/app/.venv
      - .:/app
    ports:
      - 8023:8022
    environment:
      # - ENV=production
      - DATABASE_HOST=db-pool
      - DATABASE_PORT=5499
      - DATABASE_URL=postgresql://postgres:postgres@db-pool:5499/notes_db
      - DATABASE_URL_TEST=postgresql://postgres:postgres@db/notes_db_test

  db:
    image: postgres:12
    container_name: notes-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_db
  
  pgbouncer:
    container_name: db-pool
    image: edoburu/pgbouncer
    environment:
       - DB_USER=postgres
       - DB_PASSWORD=postgres
       - DB_HOST=db
       - DB_NAME=notes_db
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres
       - LISTEN_PORT=5499
       - VERBOSE=1
    ports:
      - "5432:5499"
volumes:
  postgres_data:
  venv:
