version: '3.9'

services:
  api:
    build: .
    image: notes-api
    container_name: notes-api
    # command: sh -c "alembic upgrade head && uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8022"
    volumes:
      #This mapping was done to sync virtual environments between host and container. Reload functionality breaks without this
      - venv_data:/app/.venv 
      - .:/app
    ports:
      - 8022:8022
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/notes_db
      - DATABASE_URL_TEST=postgresql://postgres:postgres@db/notes_db_test
    # These lines has been added to enable the use of breakpoints in debugging
    stdin_open: true
    tty: true

  db:
    image: postgres:12
    container_name: notes-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notes_db
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
volumes:
  postgres_data:
  venv_data:
