version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)-4s - %(process)d - %(name)-15s : %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    filters: []
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    filename: logs/api.log
    mode: 'a'
    level: DEBUG
loggers:
  uvicorn:
    error:
      propagate: true
    access:
      propagate: true
root:
  level: INFO
  # handlers: [console, file]
  handlers: [console]
  propagate: no
