"""add required columns

Revision ID: b3d2819a2887
Revises: ca0d53ad8eb3
Create Date: 2021-05-02 13:23:18.163465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d2819a2887'
down_revision = 'ca0d53ad8eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('notes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('notes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'updated_at')
    op.drop_column('notes', 'deleted_at')
    op.drop_column('notes', 'created_at')
    # ### end Alembic commands ###
