apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration-job
  generateName: db-migration-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: db-migration-job
          image: notes-api:latest
          imagePullPolicy: Always
          command: [bash]
          args:
            - -c
            - ./k8s/scripts/migrate-db.sh
          envFrom:
            - configMapRef:
                name: db-config
          resources:
            limits:
              memory: 150Mi
              cpu: '0.5'
            requests:
              memory: 150Mi
              cpu: '0.2'
      restartPolicy: Never
  backoffLimit: 1
