apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
        - name: db-migration
          image: 450543847015.dkr.ecr.eu-central-1.amazonaws.com/notes-api:latest
          imagePullPolicy: Always
          command:
            - /bin/sh
            - -c
            - |
              echo "Attempting to run Database Migrations."
              while ! nc -z $DATABASE_HOST $DATABASE_PORT; do 
                  echo "Waiting for Database to Start..."
                  sleep 0.1; 
              done;
              echo "PostgreSQL started"
              echo "Running Database Migrations."
              alembic upgrade head
              echo "Completed Database Migrations."
          envFrom:
            - secretRef:
                name: rds-credentials
          resources:
            limits:
              memory: 150Mi
              cpu: '0.5'
            requests:
              memory: 150Mi
              cpu: '0.2'
      restartPolicy: Never
  backoffLimit: 4
